### ISSUE TITLE
Even more php 7.4 errors

### ISSUE THREAD

**Issue by brainfoolong** [matomo-org/matomo#15288]
Here are more php 7.4 errors running on 3.13.0

	19-Dec-2019 05:26:43 UTC] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in C:\www\piwik\vendor\piwik\ini\src\IniReader.php on line 236
	[19-Dec-2019 05:26:43 UTC] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in C:\www\piwik\vendor\piwik\ini\src\IniReader.php on line 250
	[19-Dec-2019 05:26:43 UTC] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in C:\www\piwik\vendor\piwik\ini\src\IniReader.php on line 250
	[19-Dec-2019 05:26:43 UTC] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in C:\www\piwik\vendor\piwik\ini\src\IniReader.php on line 257
	[19-Dec-2019 05:26:43 UTC] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in C:\www\piwik\vendor\piwik\ini\src\IniReader.php on line 259
	[19-Dec-2019 05:26:44 UTC] PHP Notice:  Trying to access array offset on value of type int in C:\www\piwik\core\Tracker\Db\Mysqli.php on line 50

**Comment by sgiehl** [comment]
the deprecations in ini component were fixed in https://github.com/matomo-org/component-ini/pull/10

**Comment by brainfoolong** [comment]
Thx for info. This deprecated fix seems rather old. Should it already be in 3.13.0?

**Comment by Findus23** [comment]
@brainfoolong Actually it hasn't been fully fixed until https://github.com/matomo-org/matomo/pull/15204 which will be released in the next release (or should already be in the beta)

**Comment by tsteur** [comment]
@Findus23 not sure if the component ini composer package has been updated in core already in the Matomo repository?

**Comment by Findus23** [comment]
@tsteur I think it has, but for whatever reason the code in https://github.com/matomo-org/matomo/pull/15204 is used instead of the ini component and therefore the warning is still thrown. I think that function can be deleted, but I don't know for sure.

**Comment by tsteur** [comment]
@Findus23 if I see this right https://github.com/matomo-org/component-ini/pull/10 was merged end August but there was no new release for the ini component since then? https://github.com/matomo-org/component-ini/releases

**Comment by sgiehl** [comment]
We would need to merge that into a new 1.x release. As the 2.x releases will be used for Matomo 4 only...

**Comment by tsteur** [comment]
created a 1.x-dev branch in https://github.com/matomo-org/component-ini/compare/1.0.6...1.x-dev and then released 1.0.7... we will need to update composer.json to include that version

**Comment by tsteur** [comment]
also need to merge https://github.com/matomo-org/matomo-php-tracker/pull/52/files and create a new release
